import { runExecuteRouteTests, runHealthRouteTests } from './modules/routes.test';
import { runValidationTests } from './modules/validation.test';
import { runErrorHandlingTests } from './modules/errorHandling.test';
import { runResourceMonitorTests } from './modules/resourceMonitor.test';
import { runEnvValidationTests } from './modules/envValidation.test';
import { runConfigTests, runLanguageCommandsTests } from './modules/config.test';
import { runErrorHandlerMiddlewareTests } from './modules/middleware.test';
import { runExecutionQueueTests } from './modules/execution.test';
import { runSecurityTests } from './modules/security.test';

runExecuteRouteTests();
runHealthRouteTests();
runValidationTests();
runErrorHandlingTests();
runResourceMonitorTests();
runEnvValidationTests();
runConfigTests();
runLanguageCommandsTests();
runErrorHandlerMiddlewareTests();
runExecutionQueueTests();
runSecurityTests();
